name: Code quality

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  typescript:
    name: TypeScript Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2.4.0

      - name: Set up Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 14
          check-latest: true
          cache: npm

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run TypeScript build
        run: npx tsc --noEmit --incremental false --tsBuildInfoFile null

  rollup:
    name: Rollup Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2.4.0

      - name: Set up Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 14
          check-latest: true
          cache: npm

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run Rollup build
        run: npm run build

  jest:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2.4.0

      - name: Set up Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 14
          check-latest: true
          cache: npm

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run jest
        run: npx jest --coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v2.1.0
